machine:
  network:
    hostname: talos-cp-01
    interfaces:
      - interface: eth0
        addresses:
          - 10.0.70.70/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.70.1
  install:
    disk: /dev/sda
    image: factory.talos.dev/nocloud-installer/95d432d6bb450a67e801a6ae77c96a67e38820b62ba4159ae7e997e1695207f7:v1.11.1
    wipe: false
  kubelet:
    clusterDNS:
      - 10.96.0.10
    extraConfig:
      serverTLSBootstrap: false
      maxPods: 250
  sysctls:
    net.core.bpf_jit_enable: "1"
    net.ipv4.conf.all.rp_filter: "0"
    net.ipv4.conf.default.rp_filter: "0"
    net.ipv4.ip_forward: "1"
    net.ipv6.conf.all.forwarding: "1"
    net.ipv4.conf.all.accept_local: "1"
    net.ipv4.conf.all.arp_announce: "2"
    net.ipv4.conf.all.arp_ignore: "1"
    net.ipv4.fib_multipath_use_neigh: "1"
  kernel:
    modules:
      - name: br_netfilter
      - name: overlay
      - name: ip_tables
      - name: iptable_nat
      - name: iptable_filter
      - name: iptable_mangle
cluster:
  allowSchedulingOnControlPlanes: true
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0
  etcd:
    advertisedSubnets:
      - 10.0.70.0/24
    initialCluster: talos-cp-01=https://10.0.70.70:2380,talos-cp-02=https://10.0.70.71:2380,talos-cp-03=https://10.0.70.72:2380
    initialClusterState: new
  apiServer:
    certSANs:
      - 10.0.70.70
      - 10.0.70.250
      - localhost
      - 127.0.0.1
  controlPlane:
    endpoint: https://10.0.70.250:6443
    localAPIServerPort: 443
  clusterName: talos-k8s
  network:
    cni:
      name: none
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
  proxy:
    disabled: true
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0
