machine:
  network:
    interfaces:
      - interface: eth0
        addresses:
          - 10.0.70.70/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.70.1
        vip:
          ip: 10.0.70.250
