apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-kubernetes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amillerrr/k8s-talos-proxmox
    targetRevision: HEAD
    path: clusters/production/apps/hello-kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
