apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - announce.yaml
  - ip-pool.yaml

commonLabels:
  app.kubernetes.io/component: cilium
  app.kubernetes.io/managed-by: argocd
