apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - default-deny.yaml
  - allow-dns.yaml

commonLabels:
  app.kubernetes.io/part-of: network-policies
  app.kubernetes.io/managed-by: argocd
