apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: router-peer-config
spec:
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 120
  # eBGP multihop if needed
  # ebgpMultihop: 1
  
  # Timers
  timers:
    connectRetryTimeSeconds: 120
    holdTimeSeconds: 90
    keepAliveTimeSeconds: 30
  
  # Address families to negotiate
  families:
  - afi: ipv4
    safi: unicast
    advertisements:
      matchName: "bgp-advertisements"
  
  # Optional: Add authentication if needed
  # authSecretRef:
  #   name: bgp-auth-secret
