apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
spec:
  advertisements:
  - advertisementType: "Service"
    service:
      addresses:
      - LoadBalancerIP
    selector:
      matchExpressions:
      - key: io.cilium/bgp-announce
        operator: NotIn
        values: ["false"]
    attributes:
      communities:
        standard: ["64512:100"]
  - advertisementType: "PodCIDR"
    attributes:
      communities:
        standard: ["64512:200"]
