apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
spec:
  blocks:
  - start: "10.0.70.230"
    stop: "10.0.70.255"
  serviceSelector:
    matchExpressions:
    - key: io.cilium/bgp-announce
      operator: NotIn
      values: ["false"]
