# https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
cluster:
  name: talos-k8s
  id: 1

kubeProxyReplacement: true

# Talos specific
k8sServiceHost: localhost
k8sServicePort: 7445
securityContext:
  capabilities:
    ciliumAgent: [ CHOWN, KILL, NET_ADMIN, NET_RAW, IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID ]
    cleanCiliumState: [ NET_ADMIN, SYS_ADMIN, SYS_RESOURCE ]

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

# https://www.talos.dev/latest/talos-guides/network/host-dns/#forwarding-kube-dns-to-host-dns
# https://docs.cilium.io/en/stable/operations/performance/tuning/#ebpf-host-routing
bpf:
  hostLegacyRouting: true

# https://docs.cilium.io/en/stable/network/concepts/ipam/
ipam:
  mode: kubernetes
  multiPoolPreAllocation: ""

# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

#debug:
#  enabled: true

# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 20
  burst: 100

l2announcements:
  enabled: false

bgpControlPlane:
  # -- Enables the BGP control plane.
  enabled: true
  # -- SecretsNamespace is the namespace which BGP support will retrieve secrets from.
  secretsNamespace:
    # -- Create secrets namespace for BGP secrets.
    create: false
    # -- The name of the secret namespace to which Cilium agents are given read access
    name: kube-system
  # -- Status reporting settings (BGPv2 only)
  statusReport:
    # -- Enable/Disable BGPv2 status reporting
    # It is recommended to enable status reporting in general, but if you have any issue
    # such as high API server load, you can disable it by setting this to false.
    enabled: true
  # -- BGP router-id allocation mode
  routerIDAllocation:
    # -- BGP router-id allocation mode. In default mode, the router-id is derived from the IPv4 address if it is available, or else it is determined by the lower 32 bits of the MAC address.
    mode: "interface"
    # -- IP pool to allocate the BGP router-id from when the mode is ip-pool.
    ipPool: ""
  # -- Legacy BGP ORIGIN attribute settings (BGPv2 only)
  legacyOriginAttribute:
    # -- Enable/Disable advertising LoadBalancerIP routes with the legacy
    # BGP ORIGIN attribute value INCOMPLETE (2) instead of the default IGP (0).
    # Enable for compatibility with the legacy behavior of MetalLB integration.
    enabled: false

externalIPs:
  enabled: true

loadBalancer:
  # https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#maglev-consistent-hashing
  algorithm: maglev
  mode: dsr

gatewayAPI:
  enabled: false
#  enableAlpn: true
#  enableAppProtocol: true

hubble:
  enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
    enableOpenMetrics: true
    port: 9965
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
  ui:
    enabled: true
    rollOutPods: true

ingressController: { enabled: false }

clustermesh:
  apiserver:
    metrics:
      enabled: true
      port: 9962
      serviceMonitor:
        enabled: true

# mTLS
authentication:
  enabled: false
  mutual:
    spire:
      enabled: false
      install:
        server:
          dataStorage:
            storageClass: cilium-spire-sc

dashboards:
  enabled: true
