apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.3/manifests/install.yaml

patches:
  # Change service to LoadBalancer
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: argocd-server
  
  # Patch the existing ConfigMap to add our settings
  - patch: |-
      - op: add
        path: /data
        value:
          server.insecure: "true"
          application.namespaces: "*"
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
