apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system  # Important: these resources go in kube-system

resources:
  - rbac.yaml

commonAnnotations:
  app.kubernetes.io/part-of: cert-manager
  app.kubernetes.io/managed-by: argocd
