apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - network/kustomization.yaml
  - controllers/kustomization.yaml
  - storage/kustomization.yaml
  - monitoring/kustomization.yaml
