apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - network
  - controllers
  - storage
  - monitoring

patchesStrategicMerge:
  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: ApplicationSet
    metadata:
      name: network
      annotations:
        argocd.argoproj.io/sync-wave: "0"
  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: ApplicationSet
    metadata:
      name: controllers
      annotations:
        argocd.argoproj.io/sync-wave: "1"
  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: ApplicationSet
    metadata:
      name: storage
      annotations:
        argocd.argoproj.io/sync-wave: "2"
  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: ApplicationSet
    metadata:
      name: monitoring
      annotations:
        argocd.argoproj.io/sync-wave: "3"
