apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.5.*
    helm:
      values: |
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
          defaultDataLocality: best-effort
        defaultSettings:
          defaultReplicaCount: 2
          storageOverProvisioningPercentage: 100
          storageMinimalAvailablePercentage: 10
          guaranteedEngineCPU: 0.1
          # Use local storage only, no external backup
          backupTarget: ""
          backupTargetCredentialSecret: ""
          # Storage settings for local disks
          defaultDataPath: /var/lib/longhorn
          dataLocality: best-effort
          replicaAutoBalance: best-effort
        ingress:
          enabled: true
          ingressClassName: nginx
          host: longhorn.k8s.local
        # Resource limits to work within local storage constraints
        longhornManager:
          priorityClass: system-node-critical
        longhornDriver:
          priorityClass: system-node-critical
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
