apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.13.*
    helm:
      values: |
        fullnameOverride: sealed-secrets-controller
        # Ensure the controller runs on control plane nodes for security
        nodeSelector:
          node-role.kubernetes.io/control-plane: "true"
        tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # Enable strict auth
        commandArgs:
        - --update-status
        - --key-renew-period=720h
        # Metrics for monitoring
        metrics:
          dashboards:
            create: true
            namespace: monitoring
        serviceMonitor:
          create: true
          namespace: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
