# Loki Configuration
loki:
  enabled: true
  
  # Use simple scalable mode for homelab
  deploymentMode: SingleBinary
  
  loki:
    # Authentication disabled for homelab simplicity
    auth_enabled: false
    
    # Common config
    commonConfig:
      replication_factor: 1
      path_prefix: /var/loki
    
    # Storage config
    storage:
      type: 'filesystem'
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
    
    # Schema config
    schemaConfig:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    
    # Limits
    limits_config:
      retention_period: 168h  # 7 days
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      max_query_parallelism: 32
  
  # Single binary deployment
  singleBinary:
    replicas: 1
    
    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    
    # Persistence
    persistence:
      enabled: true
      size: 10Gi
      storageClass: local-lvm
    
    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 10001
      fsGroup: 10001
      readOnlyRootFilesystem: true
    
    # Extra volumes for tmp
    extraVolumes:
      - name: tmp
        emptyDir: {}
    
    extraVolumeMounts:
      - name: tmp
        mountPath: /tmp
  
  # Gateway (nginx) for Loki
  gateway:
    enabled: true
    replicas: 1
    
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    
    service:
      type: ClusterIP
      port: 80

# Promtail Configuration (Log collector)
promtail:
  enabled: true
  
  config:
    # Scrape logs from all pods
    clients:
      - url: http://loki-stack-gateway/loki/api/v1/push
    
    positions:
      filename: /tmp/positions.yaml
    
    scrape_configs:
      # Kubernetes pods
      - job_name: kubernetes-pods
        pipeline_stages:
          - cri: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Add namespace label
          - source_labels: [__meta_kubernetes_pod_namespace]
            target_label: namespace
          # Add pod name label
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          # Add container name label
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          # Add node name label
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
      
      # Systemd journals
      - job_name: journal
        journal:
          path: /var/log/journal
          max_age: 12h
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
          - source_labels: ['__journal__hostname']
            target_label: 'hostname'
  
  # Resources
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  
  # Security context
  securityContext:
    runAsUser: 0  # Required for reading logs
    runAsGroup: 0
    readOnlyRootFilesystem: true
  
  # Extra volumes
  extraVolumes:
    - name: journal
      hostPath:
        path: /var/log/journal
  
  extraVolumeMounts:
    - name: journal
      mountPath: /var/log/journal
      readOnly: true
  
  # Tolerations to run on all nodes
  tolerations:
    - effect: NoSchedule
      operator: Exists

# Grafana integration (disabled since we're using kube-prometheus-stack's Grafana)
grafana:
  enabled: false

# Prometheus integration
prometheus:
  enabled: true

# Fluent Bit (alternative to Promtail, disabled by default)
fluent-bit:
  enabled: false

# Log Gateway (disabled, using Loki's gateway)
loki-canary:
  enabled: false
