apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml

commonAnnotations:
  app.kubernetes.io/part-of: monitoring-stack
  app.kubernetes.io/managed-by: argocd
