---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBe7ksWDXbVe9YxEEbTnH/P8P3eJymhu+6bY8QCO9Jk0OuNM5OIlSnJVRFa+tZ+akFU/n78znkwEzXbt4CenlbCty99tQFAU85ZbZjvTETn4U6b8tQJAxSev4J9HKCfyYWQrY0XaY3+oA/Az7Nei0qR53h9HwPF/0NV/8P9R6YKnbGzBO9LW/gknR7FdOz0johrdzyjAOuVOfJyfZro/3KOHwg8vuDOZo8lkf1+msmYGrUKGuwpj/3kGwY3SH//sSBXTlVm/bbANRgPHGQV6tBzZgWJbgR1ahsS5zOQfqG4ol/eXOxPGy+k386VhhT032KSnSIqGNcGiwf95M0FJw38A3VPOabaJcqlVo718EKiak+xrUiOymUDw3qsF+AoRTkRK5Uyz07iBDd1yv8Dg9doPdoQQNfWoMJCVPzWcDwOwIaDsp+wmvkZH+GgvXyIPONvpufbgo1R3H0m8v1SAE8fXkvvohq+2iIIXHvQV78PBIsJ8kCaZTAdQ7d5moSkhm41yexmzrOHNlpMOFn0dt9OhUWZEkMr1P6AMXd/9D9hO0CztqfBDzqrtF7GxCsGMxZj9Xyp+3HfrL8A7BBfd16hYCvdTFxTwWy+/j81NJ3SlFCLithqGcIJx461+xwMOXkIxf195b3ue4YgyZY0oGJDFmn7uLveHZdzDtz5u2xXsS2dvj9pYGRcT1u2NcCpNMjOx7jwLn7pKeSiJxMXcqDaxDUwSzGEHb5UMZ2hux9siKIYrBFT1H7d
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
