---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBG7oWua0nunkS/4Kja++R4BPTrruORubk2IExV/0eS77AC+rfuiRFlxUnWE0zRoVoNqjDBclAkAwAhcYjGiHP19zKJZK5cWmCcPMQ94sxHuE+ADwcXKV3FZDiuJJKJgETTHFq8pGgGOWXpLjx486UpeWlfW8c2mwBnT0xZpuQ3TFIkRZIQfmR+x5PuQ5GhpKYzT2T3BG25Mekdv1hTmZESIiI4Lqmwq6J3j3TMIc58doa9FV7aVN5ZZllzH1yW9XgC1TeoJNP0ahzC1BKUb2N2qTA0OkfKBdQ7mHrT1hpbIOcCIf4JYAHtH1gmJo8/MaU7pUiydH+/cScHlw+qyuCsAqmtb915iENij7dvtlGKKMUMlWQ7G05Rd8QsCYwrMKsN0xw1ocPoPXOaMV6dlCukqAGHEwqoAvJIAkQt/rtIO+bqU4I4eFE2dnAqYx2sj38d2dHy3yK/skYl9x1wFHpuEDLW3mogAZhJ+cjleY1NK15STpZWQzoDCkGl2IeRSm/HN/lzvB6SRHz8kOS5FWPa+OVAR8lfVMNhabOj9KbqIBJmtMIgq2HHP4B3E80J1yn4haUctzEbNYk00EriM1gwDd2rylRMjO0ZghpQjsiMVYaun0o4lTt4Gb8k5S2BDtOAQHcXwjdMC3qTHyHwiHLhrFvVEafKBHNBykfKBfgCiRHKRBOGhWjtILNtDwPynnh7GeCcBWN+9x/FHM0qi3eAn87IgI7YwXJg1AGIL6BBBMfOyvOyWKn3
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
