---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB/WFM3ASj0XzwbjLeWffTx3g9Zywd6G4v8x32mT1g+zvEB8pkawEkWYtyiN+tX1LK2fQX9ms27AJrHjyLxNa3n18x4PS49GOtL0bDnx/1nZJdF6Sl/PvM5X+GsR/h7THSWW7BymAa/QrCYkA7ri8I+P0DGMjbH3MQG+sgjx46Xh2hqA8G0k7qa+WoA1c/HKCaWmrDmtF/2RSn5LH6qXuMihKUpFxELK4y1o6l8/11ifE5fuoj5dcFaI4iJiwRDD4c1r/sTDy2tRDek6hmC23LGpSkaS46HyCXNCGCZpVxRnIX3UsX9WwG+bZcPEJdrzaAyAz6rzb7Z3h/TWkUWk/bA/+d0hAFj9klaflb+ZMRuN517WWN9Gs8kcZ6tKX6eOo4eR04EykB+auD6qqNS56PJYX4VTdZQtgd6GwB4OZFZkx/0MZL5e7+z81gWfbdTs8DyMdgADFxbNfkQ/hprYzr3e25MN06lADdPGIbY5aAS4EHYh27n3r3qCLJeyYQWgZ/7Vct04tVCc+6fGu/QNwCyko1+PjEEIxPKAaAr2hvmqTfzVmgKCRo3qKQLkoi8s+lhJ/lPtJMoX2YlMcSbJ3LRG5eOWWl540X+jPcDhSHKFp1z4tz0Ts4dMKK7D2g6DJqMqvmEWVIjH1iEddLfvFGcKVLCzIU5cY9EOfwJ/c9rvCUJmIoGCGmz5icVcnNnRn9Cg6at6dSHXt1/PJipTHv085XYdLB8D679QeFm9aoB4sbP4eYvCLt5
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
