---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA8b13YTQLcFRk8So/P65WQ603/X88HF2RjExGlkqNfznmHkFWv1DxJROwbbR2KekARwft7Y/0xqs94vgFmYvACr94fcsN2lqoj8xmYsbYUN19l+PRWbtC4XxMNKRUTB4/YPEGl1oeEtTJwAdN0EyHVgVurkmMY9sKlC+XxZ1tcba95oD0dYuAdOG133fDOFhzQ1QiV863NU8f3fQDbBEOhmDRdh25hJATDh7P0Q6tGheVplhoix/9JxC2uBMXXrdeYNK6iCSOaLEo8CqtoWOUHPOB5ghLLFUoc8tlc9E2ttqP9ZlQfcBiqXsJjVpVrrsdWdVNjfOo9G3L1m7kqUEkSeXJOaViHTMebbEyhYrIRT9y+T4JL71fK9+PplLCAEsGWTJfw1b2QNpL2nk2mRMkWsuDQwDo/Ff4vlXrLi3vNKeeiFYZT7ByuHnLQVA7RZCIpUsmlMte/pCUr+9I/W9hIsVtMEdxiTsSZsYqXGNcAMLXqqs4VstQSQliiScYXIlwG3cxy/xOFidxNRGKxaJvQktjRcvOHw8Gqv0p7/C0cGYV7qPiEqU/LVqBWIHH+sKH1seewkIcyQ/lVISMdVZmGnJMO0c0XjQXc7V+Cfe0pyz3hW0ZgHEVXlH+iO8OKwkoCd6j7KfnUjc6sPK9V+gzHHlslGTr058Us+OrJhHln6ObLwPYi1ve6SCffQSyoJuQE3vq27kd5qw3vIOjnGINGLe68kLK1bX2jD1i2KWqzKsAPBIO6UsXM
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
