---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAr8u8Jq9fpkrYoULHZ0h4zgTAVitbU7cl2tD+kST7h3VISrQNg9pYAbjhEpw69jdN6VI1tiakTKWzWJVuSMjplkyVSnzF8BL673hAF2hEOYyz/d0AuJOllZKVPh5xhKqyRVNaJs8a3/5Mxvc+m25zYHUD+aJGaldLAol6v4sHGfqGYMsKdS3iQZpputO8SesYwIXY4i51s/priecsA1HF+l5eOhh/XU0cBWALM1G2LgzCQPQkMs9ThRdMqJ3uIiz5bsWh4pzmo1a7Ygv0zFolSbODjQ6UWxEHHYvswJ3q8EN4pzhW4V3uQi5SLon7zdqutr5OylUMmowbuJ0vkFbVR+Gb3dVCnlkVYFuJaFLDSNi5xMV593Nji+UE4y3yKtayEBCW0A/tmsLx8hDcDMf71PG/95jwnbn17faEe/ItYIxLhJxtwHMHTXD3I5FFlFkXYji2mm1lV931auiUwtHUt9zQohcgVGpjyHV8QwSmC4LX6P2TWUgXchvQ0TZfPMU4f4hXoj05Q94+MylyFKV0mhABqUr4NkAWulsPEeU1EnanwIOs35F6oMDooW1/yA3d8E7r47Gkdal/Fz2K1Pda0HZnhtHkGB5HMgTzIOPaB4PT4N6MiwP+elBDa8KWkwsK8cyhW2igRdRPx3w/I1QlGUgqiHiQ7/gdO8b5xUdPxaofYw8lwQRDt+Pin0kve+TnBuS1xgqmwcsqlS7yG6G/7BGkQqNpu85FH6VyR9RMGKEozLEdKlL//
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
