---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCKGeXbATrvOk5H0SgvNmrosWG10501e8J7sb7K/eoB8TvPv3TgFSU3vC4bRE9TfaRPBUge3BLpmkMQjbkxCGcChFhaaHb3zmhIq4Pjhcmq4hB9Phu1zCiJ0ukOuyrpu+E9mhcB142MTmZMNyqwqOcPZfMaqNFfHiuE+5gWXeMmukITdhPp/Z8zp0ia4MXcnO19y3abUoMOPw0IXZ2f9KEHeCjRSoGUmQkybU9KBa826ikpPr5xfTkkLSa+I7wS2pcjD0emZze1PjaoLDHm7Jg6iSqp5m8XafuJ80CPTEnGaiPtGn4ZPUKkvngpFVnLHPbme70NnrRjrGcS7RrxvFns0HiPfmNMI5LZG0dLOWhctkCB0dS8PtSeJo0OlkSIYdf97CwYR5ECW7KWGrD804GylyXIswKkA1SjJ2UrJ/pS/Lt+Q7D7i8GjiBob2ZdIElvJJdcc6yQ3gIatA9jk3ylJeW6rPXBXPwVHEPh/lqUHpDFGHx8zUJ17j0GvWimbSkNR1ifHep1o9uyRb3mIIA3/SPMIDTe6vx5/rSL3ok3Syo66859iuafy0BAHVJGZRlkipJG7G7Ng5uxz5mh9HWaFcKB9KfrvsrPu/moH2PSDqi3hJioxhfGUdA9iKN3R4N4f+CRRfkKwjGYxdIQ4/bw+tHC84DgA2xSYDjXTEu0mvejrtKTFoglQFloGBtt+P1cZplH6ujpRlzoILwyGVJqpy0mCSP7iXZ47uu3wT22/HGhOcZncDPJk
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
