---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCYjJsqKAwLcvsJMOMN2UzN0Bpf0hsvNpyQITOC8GneV56Vc6whJrADvPNoJ5/h9K2c+rLNL1c5C7xY4wWaU2+38+oq5pYrUVGq4CQS+mHVdXJ26Yr86u1rblQIgUuKt96QRAgeBJyDK5czyPrhiIlQ/4JTE7C1sARv62E25a39yvrdpexfi8SU1GpO2MUkYa/1fXwSUQcNE2xaTaJ5usY4x14hY0AplUYL4iSDN5WjMr0QgZsm/l7jcIPpT5DZgt/wEBmZVNMW03ZXKI3wKT2/byyRCguD7XGsEywqbNgvSGcvAbdZ9GIqbsY6GO33sleuoOHaq/sInWsA6YodJCTitZmppE4ZZdw1dbsDQ6d99BGeWHQYZ2x/tM0cTR4dkpZfoLgSjzwyjQc0T2SrEbURcC22JI0hJi/AgrQp3mam+J+KyNCGjb86ZsDF6x0MrmnWxZOr25/gAfQT9AwBwiwhr0pEsHmNo2QT5zJ00fE4HZ75aFsbU1mjybiYFdzRPcemTjwB0UGmZysg2wo58Vz8KqN6VDq48MZ062ckn6HtFmFhO54nxAN0+nDdD3JpnH5Gm4vqD37LRo/8cFN94SdpZNU6Pqw3/DyfT6zkLprkkJpFNZWyNU7S8GTyCo6EPpxlxNb80wte5fPdr3kbuDtsz/GAd7aylTQB3XRsJKQcigzc+JGytGwE8TWYUPdULukaX58yXCtAC0/j4Sjj83o08awTtLP06DrZRAzptxTuMKGr+3tHTkUV
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
