apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - cloudflare-token-sealed.yaml
  - cluster-issuer.yaml

commonLabels:
  app.kubernetes.io/part-of: cert-manager
  app.kubernetes.io/managed-by: argocd
