apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cert-manager-egress
  namespace: cert-manager
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: cert-manager
  egress:
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    
    # Allow Kubernetes API server
    - toServices:
        - k8sService:
            serviceName: kubernetes
            namespace: default
    
    # Allow Cloudflare API
    - toFQDNs:
        - matchName: "api.cloudflare.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    
    # Allow Let's Encrypt ACME
    - toFQDNs:
        - matchName: "acme-v02.api.letsencrypt.org"
        - matchName: "acme-staging-v02.api.letsencrypt.org"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    
    # Allow OCSP responders (for certificate validation)
    - toFQDNs:
        - matchPattern: "*.lencr.org"
        - matchPattern: "*.digicert.com"
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
