apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storage
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: longhorn
            path: infrastructure/storage/longhorn
            namespace: longhorn-system
            wave: "5"

  template:
    metadata:
      name: '{{.name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.wave}}'
      labels:
        dev.homelab.stack: storage
    spec:
      project: storage
      source:
        repoURL: https://github.com/amillerrr/homelab-single-proxmox-node.git
        targetRevision: main
        path: 'clusters/production/{{.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
