apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: argocd
spec:
  description: Storage provisioners (Longhorn)
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'longhorn-system'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
