apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/name: nginx
  app.kubernetes.io/managed-by: argocd
