apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.15.0
    releaseName: sealed-secrets
    namespace: sealed-secrets
    valuesInline:
      fullnameOverride: sealed-secrets-controller
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      commandArgs:
        - "--update-status"
      serviceMonitor:
        enabled: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 65534
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
      priorityClassName: system-cluster-critical
