apiVersion: v1
kind: ServiceMonitor
metadata:
  name: api-service-metrics
  namespace: microservices-demo
spec:
  selector:
    matchLabels:
      app: api-service
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics

---
