apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-service-pdb
  namespace: microservices-demo
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: api-service

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: microservices-demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
