apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/amillerrr/homelab-single-proxmox-node.git
    targetRevision: main
    path: clusters/production/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
