---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBv604tdj53gKARnuschfpEADADJoFkKwE/Sw+6DnAQsGBKOoiwv9rA5AytwGmqDDsDhkj0bLo2iqBjW3QyaXL3/L0k3mCasCai/hKGSDQyivw2gAJ95jpvWwekCIEy8EMktWZC8lwXcn/JuBGuy4oBdood0C9Vs6bEY0haQHh/sjaTWXuE+8wGy7M8RI6+5YY9bqvVSPNiat4TF+pKBmiRXHHkaPMni3hBB8k0fYone2cIvvycpKnH+z0LVkhe2b6CO9U/QgcXMsCdBhylWvPYJRNxw/Ure30Ussko15zSmT+Pr0gFHJkBcvL6N6NaL36xHwUa6GCuLcVzU7ZyVfTra+5GGu70PpvJUqfO5x/PTPmJtPNTHpgStC178w6ojWWB2xipJgnd1g15FaR2Ca5MKIjMErsbEHpZ0+8khHjoER6abM7aswdWP7ruPWL3TAX5R7G1PU2C5VviaglYZSWx3vpZYeMzUFppeUcKBjAjzBFEWClMPay/GPhloul37xDF/zWlYTVyN/8LgLcNTurxZU11SrF9Pqwmm0IbwSThloOJci3Ty44qLM7mevm0x5i4fv6oo+vbyW6vhFEPUANB9IbRLZGXNrYjx/DAGuKAUGDu/gnS5gaGUzRSRJ9R2UKtLy/0bzvMLeL9CRcbiM9ZGvdR/s8VmfNNyk37IMArmc82f4c7vvjs0qmxHRwnpMOOjOVUEfl4YO5b9EQ2IgQZD490dE+FoHYsPrcExj9aoFiHKCBedDHd
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
