---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCMKbxpNrD9qQm9YL2xTPIdO4aWbnWpNEhFKzh7hGmKDaR0OBsOEjOlH7SVSOlbsZ6w/xNs+7F7+/fHfVOJD5hstoSqEoZVX56ptoUBVv1nRwaIHliDzqhKINizJOIdsLQ90+/GY5ThK8DWzILZs6tzbIk0AxiFb9TWZrm8F28XzndcbBAfS+s2RnZdfI/1aP6AjvoocBxU4c/0p70vdiT2rd2q1Q3xhcgAjX1k4xPG5SIvSUs5jCd7p0kG5R0ypwo7XJstt5MLSVTbU0enWrS1rL06i0Sfvc2XYJad+rOfYXhR6VYt+JwklSpFo0ev3fObuBiy2GSxSMgzUHMBPnmTL/6SWu+ohoYelZHdikmfzmgtHg7ghajCKTxsxHtJdYkN+lZC4g4jHDw9pGzjEUScRfqAq4NO/4GYLFRw3sVZ+OaQWStQYKUA/GpMB68o3EpognGvRMn/bc9NqdpRVH35cihbX0wKgASUlANK7gSNvNQBceDzpj2Hz5Ste3l2XM6naf6Jo2KTQKATems/xDL6sZxbqw8zl8GfM6YWho2S4mK78w3SOJyPqcohDXAntGhPtlmzprNcnHJQCimOvN3rjip7zu/fa6l7G8O6A+vtlhhx3K+HZXiT2Lt3nN+QpSl0Ju2Lylnq8T516xLfqidyBVLk7GaiJ+Bhw3tnBwW7oQyXVkD8qABF/2qi8x4OWvRsBJLzRvrI0/VCed9VWSF8VutEcWw4lfjifXfY4GNPuRGyg4by/fwC
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
