---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgADmsFrPiHyvb9ZZc0q99oGuiOjp+5hX4/UZZw+SWT3poNpkqtJZPhLcIoCvxeAdWydjYpxlMKPdoJDKiy8CrF385qjLgLJtZuJ0dbKsf4rw5eTk1IJLzfA3GVYJfpU5hTic6TCnqSjdteVddAY87wPHNu9w83CaC49F987s/UlWDh5/hfFi56oXZPaH/nmpVaI2RC6ni+OoyAwnc+MULqW6c6RTYhlPOBbGr+ZXDPRnWuFlDCA4btjew7kXwRWEIOm7ht+lrPiMBeRxw7r6hGfxEF9Fq9mTnjQYV1T+ovfng+5riSxca18YgO3ilng9v5Z5aCe8Atnn/kGm7YGStKL3/aXMHG/GzTAV+J0qgx4SX8yk30jf+5/jXa+2pC22mr6z9U10dzaIVSCpDKDrd9uF+s6vt2dP+j98bD3vI+QBfTZiNGHvIfmQmlgsDNFiRPIyy0YhcJIc8Iy5S0LvemE1EsREY9JXGBTzzxBJc6pEqnfF98W5ojnNkKobsVazn2VTbDfhhcKKRf7VzEXuZxe/Ykd72EQ6y5a/oCtjPRLsHcvzcWH0kd1QB7/2qNLzPUugzMoGfBpxRpeeSxv4JsytwPOwBGz0IcFsbNyAwbOzhYbgBk9EmgEyzXjTpQE7EbOO1rEPBS0MbkIaGrhMe0EVVxm0eNp2W+4eDAdm4CLBsJogWOrmf8Ngqa6pMhxQwPEvYd5f9FyT7qERLbV0u0Wd14xMZmkKfyOrhun44bY8hDXUmH26BaV
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
