apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-test
  namespace: default
spec:
  parentRefs:
    - name: external
      namespace: gateway
  hostnames:
    - "test.mill3r.la"
  rules:
    - backendRefs:
        - name: nginx
          port: 80
