apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: monitoring
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        http:
          preferred_ip_protocol: "ip4"
          valid_status_codes: [200, 201, 202, 203, 204, 301, 302, 303, 307, 308]
      http_post_2xx:
        prober: http
        http:
          method: POST
          preferred_ip_protocol: "ip4"
      tcp_connect:
        prober: tcp
      icmp:
        prober: icmp
      dns:
        prober: dns
        dns:
          preferred_ip_protocol: "ip4"
          query_name: "kubernetes.default.svc.cluster.local"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter:v0.24.0
        args:
        - --config.file=/config/blackbox.yml
        ports:
        - containerPort: 9115
          name: metrics
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          requests:
            memory: "50Mi"
            cpu: "20m"
          limits:
            memory: "100Mi"
            cpu: "50m"
      volumes:
      - name: config
        configMap:
          name: blackbox-config

---
