apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: synthetic-monitoring
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    path: /probe
    port: metrics
    params:
      module: [http_2xx]
      target: [https://app.k8s.local]
    relabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: blackbox-exporter:9115
  selector:
    matchLabels:
      app: blackbox-exporter
