---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Monitoring stack (Prometheus, Grafana, Loki, Alertmanager)
  
  sourceRepos:
    - 'https://github.com/amillerrr/homelab-single-proxmox-node.git'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://grafana.github.io/helm-charts'
  
  destinations:
    - namespace: 'monitoring'
      server: '*'
  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
