---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: User applications and workloads
  
  sourceRepos:
    - 'https://github.com/amillerrr/homelab-single-proxmox-node.git'
    - '*'  # Allow any Helm chart repository for flexibility
  
  destinations:
    - namespace: 'default'
      server: '*'
    - namespace: 'apps-*'  # Allow any namespace starting with apps-
      server: '*'
  
  clusterResourceWhitelist:
    - group: 'gateway.networking.k8s.io'
      kind: 'HTTPRoute'
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
