apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.5.10
    releaseName: argocd
    namespace: argocd
    valuesFile: values.yaml

resources:
  - appproject-default.yaml

commonAnnotations:
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/managed-by: kustomize
