apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.3/manifests/install.yaml
  # - certificate.yaml
  - appproject-default.yaml
  - network-policy.yaml

patches:
  # Change service to LoadBalancer
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: argocd-server
  
  # Enable Helm support in kustomize for repo-server
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-repo-server
      spec:
        template:
          spec:
            containers:
              - name: argocd-repo-server
                env:
                  - name: KUSTOMIZE_PLUGIN_HOME
                    value: /usr/local/bin/kustomize/plugin
                  - name: ARGOCD_EXEC_TIMEOUT
                    value: "180"
                command:
                  - sh
                  - -c
                  - |
                    cp -r /usr/local/bin/kustomize /tmp/kustomize-copy
                    /tmp/kustomize-copy/kustomize version --client
                    exec argocd-repo-server --loglevel=debug
    target:
      kind: Deployment
      name: argocd-repo-server
  
  # Patch ConfigMap to add kustomize build options
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
      data:
        kustomize.buildOptions: "--enable-helm --load-restrictor LoadRestrictionsNone"
    target:
      kind: ConfigMap
      name: argocd-cm
  
  # Patch the existing argocd-cmd-params-cm ConfigMap
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
      data:
        server.insecure: "false"
        application.namespaces: "*"
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
