apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.15.3
    releaseName: cert-manager
    namespace: cert-manager
    valuesInline:
      crds:
        enabled: true
        keep: true
      extraArgs:
        - "--enable-gateway-api"
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
      webhook:
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
      cainjector:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

commonLabels:
  app.kubernetes.io/part-of: cert-manager
  app.kubernetes.io/managed-by: argocd
